name: Publish Package
# This workflow publishes a package to PyPI when a pull request is merged into the main branch.
on: 
  pull_request:
    types: ["closed"]
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "This job runs only if the pull request is merged into main."
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Install Poetry
      #   run: curl -sSL https://install.python-poetry.org | python3 -

      # - name: Add Poetry to Path
      #   run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # - name: Install dependencies
      #   run: |
      #     poetry install --with publish

      # - name: Publish package
      #   run: |
      #     poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}